# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd567140d483b5d99b7fa9e7b189ec2b6102c184da9fb4cdfa8419fff0f807fe1b81d5c5fc35d3e76b7cafb54d4aa2c34f1899e72e9ec92639d061d2aa0305ac

test:
  secret_key_base: 579532096f31dbc12134d5dae9df6ce33ef3b495b7a4e67513fe05c297a44609996c172e6b1fd67d6ea08442be61d0e3c55245c7b3fe85f7f86cd1811f8fd78c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
